language: node_js

node_js:
  - 6
  - 7
  - 8

services:
  - mongodb

install:
  - yarn

cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn build

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    skip_cleanup: true
    app: glab-staging-reader-admin
    on:
      branch: master
      node: '8'
  - provider: heroku
    api_key: $HEROKU_API_KEY
    skip_cleanup: true
    app: glab-reader-admin
    on:
      tags: true
      node: '8'

notifications:
  email: false
  slack:
    secure: dKXP3OrPFHuw56KcJ0rjy3KYr/zVIIZdv00vrD0vzBlKRmvl0l5UCtNIGaDb2/lcI5hD19EYcHi8fiyy4wYSB5qc3n2pSajQ8q2qSxEnsVUVojs7kLN84X1Sogjb1HRiFoOLoC20mu4FVMEhb/ryM4kLlJsd0pP2qAXkEAZlaVGXDmxOzss94xMRFSCH5S8VHhNZY0AB+NvWTxAWi75W23yWrqroxBnDrCK46dwdMx/5+KjrvcQCSU1p4VCD2jRibYI9TbeJOz/xUqQ4lNJHPqdBcsBVeqJgKpzepuh0d3hyyhE2/IMboYJ5zr0BKV8FWPJFNToMV1fZ23zbP0LzQCZrlj/YuTZ1iUrNpHVNKiGYLYva0RjbrZkxNB8lkT0Yq8bntTwOxg3xg4AHiNRC4Hp2ZMuCls6WCNmEi4vUHtRnShB8HfKf1et2Ti6CXrDgr5Oxw7VFRryEyVeabIkrRjPt+Pposbqu7gpskyuKrqTJO0zKetMytCSMBQTRLvfIeY5AaXTISR3qpFh779VmTpcxdTRo2uTr4BT9+ZCduGyDHXIjKKzigfb0eXzYZyvl99XAzxbG0lcqr/SYLj6Y8xqpt6j9PYS/qBPw8jPlySqHXHNUD+/gBdMuEb6G4e0M/Z2da7kypodo4I8MAoR64v+QEgpA+y51QZnY8TFMqC0=
